show reservations for all actor topology-embed-service state active
show reservations for all actor bbn-sm state active
show reservations for all actor rci-sm state active
show reservations for all actor fiu-sm state active
show reservations for all actor ufl-sm state active
show reservations for all actor uh-sm state active
show reservations for all actor ucd-sm state active
show reservations for all actor sl-sm state active
show reservations for all actor osf-sm state active

